### ISSUE TITLE
Petición de subida: Despliegue online con Heroku

### ISSUE THREAD

**Issue by alfalatam** [juandelaoliva/decideEuropa#14]
Relacionado con : #13 

Solicito permiso para subir a la rama principal los cambios implementados que permiten el despliegue de manera aislada de nuestro sistema con heroku

@juandelaoliva

**Comment by Bwer23** [comment]
Necesitaria acceso al codigo en una rama distinta a master para realizar las pruebas para poder validar el merge con la rama master.

**Comment by alfalatam** [comment]
@Bwer23 
Si ,perdona se me ha pasado subir en enlace.
Me esta dando algún problema github con ubuntu para subir el proyecto te lo he subido a ese repositorio comprimido ,cuando solucione el problema lo re-subiré correctamente

> https://github.com/alfalatam/decide-egc-prueba

También en este enlace tienes el proyecto ya desplegado por si quieres comprobar ,utilice la última versión de la rama de decide-europa-visualización 

> https://decide-heroku-ubuntu.herokuapp.com/doc/

Si tienes cualquier problema ,no dudes en preguntarme

**Comment by Bwer23** [comment]
El despliegue es correcto tanto en heroku como en local, puedes proceder a hacer commit en la rama principal
@alfalatam
