### ISSUE TITLE
¿Como va la integración y el trabajo con los demás subsistemas?

### ISSUE THREAD

**Issue by alfalatam** [juandelaoliva/decideEuropa#15]
Relacionado: @juandelaoliva 

Quería saber si se va a proceder a actualizar nuestra rama con la rama padre de Europa ,para ver si se integran sin conflictos nuestros cambios para poder subir nosotros también a la rama principal.
Recuerdo que para poder optar a más de un 7 se necesita trabajar con al menos otro subsistema

**Comment by juandelaoliva** [comment]
Los demás coordinadores comunican que por falta de tiempo y de falta de submódulos no se va a realizar la integración de subsistemas.

**Comment by alfalatam** [comment]
ok,cierro issue
