### ISSUE TITLE
Ampliacion de votacion a 2 o mas preguntas

### ISSUE THREAD

**Issue by Bwer23** [juandelaoliva/decideEuropa#19]
Se procedera a modificar la visualizacion de booth para permitir la votacion de 2 o mas preguntas de manera simultaneo, coordinandomos con otros moduos para su correcto funcionamiento.

**Comment by juandelaoliva** [comment]
@Bwer23 Que datos necesitas concretamente que nos faciliten para poder proceder a la implementación?

**Comment by Bwer23** [comment]
@juandelaoliva Necesitaria que modificaciones han realizado al modelo si se realizo alguna, asi como el formato en el que encapsularan laspreguntas(array,diccionario,etc)

**Comment by juandelaoliva** [comment]
Los compañeros de los otros módulos me comunican que no se va a realizar el  cambio anteriormente propuesto por falta del módulo voting y falta de tiempo
