### ISSUE TITLE
Reunión Sábado 12 de Enero

### ISSUE THREAD

**Issue by juandelaoliva** [juandelaoliva/decideEuropa#29]
Relacionado con: #17
Se convoca una reunión presencial para el sábado 12 de Enero a las 18:00 en casa de @Bwer23 

Se ruega confirmación mediante una respuesta a esta Issue.

- [x] Juan

- [x] Alfonso

- [x] Elena

- [x] Felipe

- [x] Manolo

**Comment by Bwer23** [comment]
Confirmo asistencia

**Comment by Feltrimar** [comment]
Confirmo asistencia.

**Comment by juandelaoliva** [comment]
Confirmo asistencia

**Comment by ElenaMo** [comment]
Confirmo la asistencia a la reunión
