### ISSUE TITLE
Petición de merge

### ISSUE THREAD

**Issue by juandelaoliva** [juandelaoliva/decideEuropa#32]
Relacionado con: #31 
Alguno puede confirmar los cambios y me dais el ok? están en mi rama juanDev

He cambiado parte del requirements y el link de heroku

**Comment by Feltrimar** [comment]
No está descrito lo que has hecho, por favor, indica el qué has modificado

**Comment by juandelaoliva** [comment]
corregido @Feltrimar

**Comment by Feltrimar** [comment]
Comprobado, accede al merge

**Comment by juandelaoliva** [comment]
Perfecto gracias
