### ISSUE TITLE
Peticion de commit arreglo error 404

### ISSUE THREAD

**Issue by Bwer23** [juandelaoliva/decideEuropa#37]
Cuando se intente visualizar una votacion no exixtente no mostrara el mensaje estandar de 404, sino un mensaje informativo indicando que esa votacion no existe.

Relacionado con 
#36

**Comment by alfalatam** [comment]
Relacionado con: @Bwer23 
Lo he comprobado en tu rama ,y funciona correctamente , procede con el commit
