### ISSUE TITLE
Reunión Domingo 13

### ISSUE THREAD

**Issue by juandelaoliva** [juandelaoliva/decideEuropa#38]
Relacionado con: #13 #16 
Se convoca una reunión presencial para trabajo en grupo y ultimar detalles de la entrega. Será a las 12:00 en casa de @ElenaMo.

Se ruega confirmación.

- [x] Elena

- [x] Alfonso

- [x] Felipe

- [x] Manolo

- [x] Juan

**Comment by ElenaMo** [comment]
Confirmo la asistencia a la reunión

**Comment by alfalatam** [comment]
Confirmo
