### ISSUE TITLE
He creado un Pull request para añadir campos al html de visualizer

### ISSUE THREAD

**Issue by juandelaoliva** [juandelaoliva/decideEuropa#40]
Relacionado con: #39 #38 #13 
He creado un pull request para añadir cambios en los campos del html de visualizer, Lo podeis comprobar en mi rama -> devJuan

**Comment by Bwer23** [comment]
Comprobados cambios en rama devJuan. Sin errores. Proceda al merge/commit en master

**Comment by juandelaoliva** [comment]
Gracias compañero
