### ISSUE TITLE
Push cambios "Simplificacion controlador vista" en master

### ISSUE THREAD

**Issue by Bwer23** [juandelaoliva/decideEuropa#6]
Simplificado el controlador de la vista de visualizaer para ser mas intuitivo.
Update en urls para complementar los cambios.
commit cb1b7411085b410573ea15d1c412621b56b757d4

**Comment by alfalatam** [comment]
Me da errores a la hora de abrirlo en local,¿puede ser que te falte algo por subir? #6

**Comment by Bwer23** [comment]
Revisa los modulos instalados ya que se han añadido nuevos en e0eb2341e9157b3928c837a035375a867f0dc63a

**Comment by alfalatam** [comment]
Si,me faltaba instalar la ultima libreria ,por eso me saltaba el error al hacer el migrate ,gracias
